### ISSUE TITLE
Npm test error : integration tests

### ISSUE THREAD

**Issue by Bhavikkumarpatel** [JoshMcguigan/opc-gateway#1]
When i send to websocket api : 
"readVariableValue":"ns=1 s=FanSpeed",
"browse": "RootFolder"

I got resopnce like {"statusCode":200,"body":{},"request":"\"readVariableValue\":\"ns=1 s=FanSpeed\",\n\"browse\": \"RootFolder\""}.

When i run npm test then 
![unbenannt](https://user-images.githubusercontent.com/41054577/43200576-3e081ff0-9016-11e8-91ee-73acf55bd103.JPG)

The test in Unit are passed but the integration test are failed.

The OPC UA Server and npm Start opc sever and port are running perfectly.
How can i solve this problem?

**Comment by JoshMcguigan** [comment]
How are you running the tests? `npm test` should run the unit tests only and skip the integration tests, but it looks like you are running all of the tests (unit and integration together). 

Running the integration tests requires running `npm run test:mockopc`, `npm run test:mockapp`, and then `npm run test:integration` in three separate terminals.

**Comment by JoshMcguigan** [comment]
I did just find an issue with one of the dependencies on newer npm versions as referenced by this issue -> node-opcua/node-opcua#381.

I've upped the version to solve this problem, which will help if you want to run the integration tests. You'll also need to generate the certificates required by node-opcua. I'll try to add some documentation for that.

**Comment by Bhavikkumarpatel** [comment]
@JoshMcguigan  Thank you. 

The previous version of node giving me npm version issue which you mentioned here. So, i change my node version to 0.4.2 and i am getting the test errors. But after you fix the node version everything working perfectly. Even thoug all tests are passed.

I have one Suggestion in Package.json :  "test:unit": "jest __tests__/unit" and "test:integration": "jest __tests__/integration". Could you put one space before /unit and /integration? Anotherwise it has shown no test found.

![capture](https://user-images.githubusercontent.com/41054577/43252803-af174a60-90c3-11e8-94f6-89ed5b6d8cae.PNG)

**Comment by JoshMcguigan** [comment]
Thanks for the feedback. Can you confirm you are still having the issue with the space in the tests, because I do not have that problem on node version 10.5.

**Comment by Bhavikkumarpatel** [comment]
Yes stll i have same issue with space.

When i don´t have space then it shows no test found.
When i have space then all test are run successfully.

Node -v 8.11.3

**Comment by Bhavikkumarpatel** [comment]
Hello!

Could you please provide some documents about gateway?

How to subscribe using ws://localhost:3000/subscribe?

Becuase i try to subscribe then gateway showing error and disconnected from opc.tcp.

Thanks

**Comment by JoshMcguigan** [comment]
Hi @Bhavikkumarpatel,

On the tests, can you try with node v10.5? That is the version I am running without issue. 

As for your question about documentation, I apologize but I don't really have time to actively support this crate any more. I've added a note to the readme reflecting this. 

If you are looking to deploy something like this in a production environment, I'd recommend forking this repository and updating all dependencies to the latest versions. That may be a large task, since a few dependencies are several versions outdated. 

Sorry I couldn't be of more help. I really appreciate your interest in this project.

Thanks,

Josh

**Comment by Bhavikkumarpatel** [comment]
Hi @JoshMcguigan ,

I need one help only.

In this API, allow actions are readVariableValue and browse. My question is how to reformat these two?
I mean while you send message to API and you will get particular structure. I want to modify this structure. Is it Possible to get data according to my require format?

Thanks.

**Comment by JoshMcguigan** [comment]
You mean you want to change the format that is returned to the user when they make a request right? 

If so, I believe you could update [requestHandler.js](https://github.com/JoshMcguigan/opc-gateway/blob/master/src/requestHandler.js#L14) to modify the body before setting it to the response body.

**Comment by Bhavikkumarpatel** [comment]
Hi @JoshMcguigan ,

Yes! Ok. for responce i got it.

![capture](https://user-images.githubusercontent.com/41054577/43958212-e5ee644a-9caa-11e8-95fa-3bef7ee69102.JPG)

Now! I have one IIoT Platform which sends one particular format which is shown as image. So that, i also want to format request also. Is it possible or i have to modify my platform?

**Comment by JoshMcguigan** [comment]
That would also be possible. At that point you would have mostly rewritten the opc-gateway, so you may just consider starting from scratch with updated dependency versions, while using opc-gateway as a reference.

**Comment by Bhavikkumarpatel** [comment]
Hello @JoshMcguigan 

Is that writing value is possible with your websocket?
Could we sent request like readVariablevalue or browse for writing?
Do you have any Idea about it? I tried but not getting the result.

Thanks!

**Comment by JoshMcguigan** [comment]
Writing values is not currently supported.
